version: '3.4'

services:
  be:
    restart: always
    build:
      context: ./backend
      network: host
    ports:
      - "8002:8002"
  fe:
    restart: always
    build:
      context: ./frontend
      network: host
    ports:
      - "4200:4200"
